export const metadata = {
  title: 'Spokane Bitcoin Club',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body style={{margin: '0px'}}>        
        <main className="app">
          {children}
        </main>
      </body>
    </html>
  )
}
